VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Form_Mainpage"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Form_Click()

End Sub

Private Sub √„—0_Click()

End Sub

Private Sub Form_Load()
DoCmd.ShowToolbar "ribbon", acToolbarNo
End Sub
